### ISSUE TITLE
feat: ion-grid size

### ISSUE THREAD

**Issue by sansan88** [project-owlly/site#103]
Ion-grid CSS Property: max-size = 960px 

- >Vorallem für micropage.. oder auch landing page

**Comment by jonarivado** [comment]
Wirkt das dann nicht zu gequetscht (vor allem auf grossen Bildschirmen)? Ich finde, ein breiteres Design ist moderner.
Angehängt die Seite, wenn das Grid max-width 960px hat und die 10% padding ausgeschaltet sind (21'' Bildschirm)
![image](https://user-images.githubusercontent.com/63780364/97623656-4a25c200-1a26-11eb-8807-8d47d1fa76ea.png)
![image](https://user-images.githubusercontent.com/63780364/97623815-7ccfba80-1a26-11eb-8858-ed8d478832f7.png)

**Comment by sansan88** [comment]
Ich nehme das fürs meeting mit.

**Comment by sansan88** [comment]
![grafik](https://user-images.githubusercontent.com/2372120/97713441-22833800-1ac0-11eb-8825-25043dbd00d6.png)

**Comment by peterpeterparker** [comment]
in my branch i have/will add a style for the main content therefore don't change the styling but wrap it in the `main` content

```
<ion-content>
    <main>
      <!-- here  -->
```
