### ISSUE TITLE
feat: change feedback icon. 

### ISSUE THREAD

**Issue by sansan88** [project-owlly/site#118]
https://ionicons.com/

`<ion-icon name="megaphone-outline"></ion-icon>`

**Comment by sansan88** [comment]
based on user feedback,. People expect a chat..

**Comment by sansan88** [comment]
@jonarivado 
Whats wrong with my icon :)

**Comment by jonarivado** [comment]
@sansan88 didn't see your comment, I'm sorry 😅

**Comment by sansan88** [comment]
Haha 😂
