### ISSUE TITLE
feat: Dark mode switch

### ISSUE THREAD

**Issue by sansan88** [project-owlly/site#142]
Theme switch does not work

**Comment by peterpeterparker** [comment]
because I did not know there was a switcher ;)

were is it? I mean in the GUI

**Comment by sansan88** [comment]
haha sorry :) I thought this was from you?

`  <a href="/" aria-label="Owlly">
        <ng-container *ngIf="theme$ | async as theme">
          <img [src]="'./assets/logo/owlly-' + theme + '.png'" loading="lazy" aria-label="hidden" />
        </ng-container>
`

**Comment by jonarivado** [comment]
@sansan88 Do you want a graphical switch for the user or is this issue just for fixing the light/dark mode problem with the logo?

**Comment by sansan88** [comment]
I think we don't need a switch for now? But would be cool to have it later.. 
For now the "fix" would be enough,..

**Comment by peterpeterparker** [comment]
@sansan88 what's the effective issue ?
can you please describe precisely what does not  work and how to reproduce the issue? 

aka: details

**Comment by sansan88** [comment]
@peterpeterparker 
Sorry, I didn't know who changed that.. The owlly logo does not work on "light mode"

![grafik](https://user-images.githubusercontent.com/2372120/98590724-88956980-22cf-11eb-9a36-d34081fb6234.png)
![grafik](https://user-images.githubusercontent.com/2372120/98590739-8d5a1d80-22cf-11eb-8cfc-8fe12acbf8e8.png)

**Comment by peterpeterparker** [comment]
Solve. Note: if  you change your OS settings on the fly, then you have to refresh your browser (at  least for now)
