### ISSUE TITLE
feat: dark mode for newsletter page 

### ISSUE THREAD

**Issue by sansan88** [project-owlly/site#41]
dark mode in general..

**Comment by jonarivado** [comment]
![image](https://user-images.githubusercontent.com/63780364/95101328-4e660480-0732-11eb-96d9-89c230419325.png)

There already is a dark mode?

**Comment by sansan88** [comment]
check buttons slot-.
https://ionicframework.com/docs/api/toolbar

![grafik](https://user-images.githubusercontent.com/2372120/95102764-1364d080-0734-11eb-8811-bd774c0b7019.png)

**Comment by sansan88** [comment]
müssten wir die buttons gelb machen?
