### ISSUE TITLE
feat: Testpage

### ISSUE THREAD

**Issue by sansan88** [project-owlly/site#46]
Use the testpage for: 
- Enter userdata
-- name
-- vorname
-- geburtsdatum
-- wohnort
-- adresse (Strasse)
-- Hausnumemr

- Download a "Blank" PDF mit den Daten.
- Download PDF Varainte 1 (fixer download aus google drive)
- Download PDF Variante 2 (fixer download aus google drive)

**Comment by sansan88** [comment]
@peterpeterparker 
I would like to use the signature button as npm module to call the eID Login page on the test page.
Can we use it?

**Comment by sansan88** [comment]
ok, would you use **latest** as flag?

**Comment by peterpeterparker** [comment]
yes probably

**Comment by sansan88** [comment]
Hey @jonarivado 
What's the progress here? :) are you done with the testpage?

**Comment by jonarivado** [comment]
Tried to use capacitor to directly display the pdf as you've told me but I haven't figured it out yet

**Comment by sansan88** [comment]
you can use capacitor browser to display the pdf from the pdf url
you can see here: 
`            this.pdfService.generatePDF({userData: userData, owllyId: params.state}).subscribe(async (data) => {
              this.pdfGenerated = true;
              Browser.open({url: data.url}).then((done) => {});
            });`

**Comment by jonarivado** [comment]
Yes, this works! Kinda humiliating that I only needed to change one line... 
![image](https://user-images.githubusercontent.com/63780364/98596131-48d28000-22d7-11eb-98da-e9df9a1d1b1d.png)
looks like i need to take a look at the pdf generate function though, or are you already on it?

**Comment by sansan88** [comment]
@jonarivado 
didn't had the time yet to do.. 
please feel free to do it..  :-)
https://github.com/project-owlly/cloud/issues/83
