### ISSUE TITLE
fix: logo color

### ISSUE THREAD

**Issue by peterpeterparker** [project-owlly/site#97]
black on black

<img width="1393" alt="Capture d’écran 2020-10-21 à 05 54 04" src="https://user-images.githubusercontent.com/16886711/96671404-ee8e7100-1361-11eb-8663-47b95ce6a1b1.png">

**Comment by sansan88** [comment]
I think it's just a placeholder. But it would make it more difficult for other projects to provide two types of logos

**Comment by peterpeterparker** [comment]
do you plan to do some public demo and show this  page to other persons?

if  yes, then even if it's a placeholder, I would suggest to fix it

**Comment by sansan88** [comment]
yes we have a demo on friday, first with "bug bounty Schweiz"
then in the afternoon at dinacon conference
